package tunnel

import (
	"crypto/tls"
	"crypto/x509"
	"errors"
	"net"
	"strings"
)

// ConnectErrorInfo holds a user-friendly category and fix suggestion for a
// connection error.
type ConnectErrorInfo struct {
	Category   string
	Suggestion string
}

// ClassifyConnectError inspects a connection error and returns a user-friendly
// category and actionable fix suggestion.
func ClassifyConnectError(err error) ConnectErrorInfo {
	if err == nil {
		return ConnectErrorInfo{}
	}

	s := err.Error()

	var dnsErr *net.DNSError
	if errors.As(err, &dnsErr) {
		return ConnectErrorInfo{
			Category:   "DNS resolution failed",
			Suggestion: "Check that the server address is correct",
		}
	}

	var unknownAuth *x509.UnknownAuthorityError
	if errors.As(err, &unknownAuth) {
		return ConnectErrorInfo{
			Category:   "Certificate authority mismatch",
			Suggestion: "Ensure client.pem was generated by the same CA as the server certificates",
		}
	}

	var certInvalid *x509.CertificateInvalidError
	if errors.As(err, &certInvalid) {
		return ConnectErrorInfo{
			Category:   "Invalid certificate",
			Suggestion: "Certificates may be expired or corrupted. Regenerate with: pantyhose-server gencert",
		}
	}

	var hostnameErr x509.HostnameError
	if errors.As(err, &hostnameErr) {
		return ConnectErrorInfo{
			Category:   "Certificate hostname mismatch",
			Suggestion: "Server certificate does not match the address. Regenerate with: pantyhose-server gencert --hosts <server-ip>",
		}
	}

	var recordErr tls.RecordHeaderError
	if errors.As(err, &recordErr) {
		return ConnectErrorInfo{
			Category:   "TLS handshake failed",
			Suggestion: "Server may be running in --insecure mode while client expects TLS",
		}
	}

	var opErr *net.OpError
	if errors.As(err, &opErr) {
		if opErr.Timeout() {
			return ConnectErrorInfo{
				Category:   "Connection timed out",
				Suggestion: "Check network connectivity and firewall rules on the server",
			}
		}
	}

	if strings.Contains(s, "connection refused") ||
		strings.Contains(s, "actively refused") {
		return ConnectErrorInfo{
			Category:   "Connection refused",
			Suggestion: "Ensure pantyhose-server is running on the target host and port",
		}
	}

	if strings.Contains(s, "no route to host") || strings.Contains(s, "network is unreachable") {
		return ConnectErrorInfo{
			Category:   "Network unreachable",
			Suggestion: "Check network connectivity and VPN status",
		}
	}

	if strings.Contains(s, "connection reset") {
		return ConnectErrorInfo{
			Category:   "Connection reset by server",
			Suggestion: "Server may have rejected the client certificate or crashed",
		}
	}

	return ConnectErrorInfo{
		Category:   "Connection failed",
		Suggestion: "Check network connectivity and server status",
	}
}
